# -*- coding: utf-8 -*-
"""t:conbool,logic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4jhPwbxlQPtthnfjyBhb62_a2nY6vF9
"""

# Input
student_name = input("Enter student name: ")
maths = int(input("Enter Maths marks: "))
science = int(input("Enter Science marks: "))
english = int(input("Enter English marks: "))
# Validation
if maths < 0 or maths > 100 or science < 0 or science > 100 or english < 0 or english > 100:
    print("Invalid marks entered")
else:
    # Calculation
    total_marks = maths + science + english
    average = total_marks / 3
    # Display basic details
    print(f"Student Name: {student_name}")
    print(f"Total Marks: {total_marks}")
    print(f"Percentage: {average:.2f}")
    # Pass / Fail check
    if maths < 40 or science < 40 or english < 40:
        print("Status: FAIL")
    else:
        print("Status: PASS")
        # Grade assignment
        if average >= 75:
            grade = "A"
        elif average >= 60:
            grade = "B"
        else:
            grade = "C"
        print(f"Grade: {grade}")